const VALIDATION_VALUES={
    MIN_LENGTH_PASSWORD:6,
    MAX_LENGTH_PASSWORD:255,
    MAX_LENGTH_NAME:50,
    MAX_LENGTH_EMAIL:255,
    MIN_VALUE_ID:1,
    MIN_LENGTH_COMMENT:4
}

module.exports={VALIDATION_VALUES};