const VALIDATION_VALUES={
    MIN_LENGTH_PASSWORD:6,
    MAX_LENGTH_PASSWORD:255,
    MAX_LENGTH_NAME:50,
    MAX_LENGTH_EMAIL:255,
    MIN_VALUE_ID:1,
    MIN_LENGTH_COMMENT:4,
    MAX_LENGTH_COMMENT:500,
    MIN_LENGTH_TITLE_POST:5,
    MAX_LENGTH_TITLE_POST:200,
    MIN_LENGTH_CONTENT_POST:20,
    MIN_VALUE_QUERY_PAGE:1,
    MIN_VALUE_QUERY_LIMIT:1,
    MAX_VALUE_QUERY_LIMIT:5,
    MIN_VALUE_QUERY_AUTHOR_ID:1,
    DEFAULT_VALUE_QUERY_PAGE:1,
    DEFAULT_VALUE_QUERY_LIMIT:4,
    MIN_VALUE_CATEGORY_IDs:1,
    MAX_VALUE_CATEGORY_IDs:20,
    MIN_LENGTH_CATEGORY_IDS:1,
    MAX_LENGTH_CATEGORY_IDS:10
}

module.exports={VALIDATION_VALUES};